In [1]:
!pip install h2o mlflow dagshub scikit-learn pandas matplotlib -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.4/266.4 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 111.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 91.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 70.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.3/273.3 kB 20.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 17.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 15.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 85.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 57.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 16.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 6.8 MB/s eta 0:00:00

In [2]:
import h2o
from h2o.automl import H2OAutoML
import pandas as pd
import mlflow
import dagshub

In [3]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.19" 2026-04-21; OpenJDK Runtime Environment (build 17.0.19+10-1-22.04.2-Ubuntu); OpenJDK 64-Bit Server VM (build 17.0.19+10-1-22.04.2-Ubuntu, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpv6ic8k8_
  JVM stdout: /tmp/tmpv6ic8k8_/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpv6ic8k8_/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.11
H2O_cluster_version_age:    2 months and 19 days
H2O_cluster_name:           H2O_from_python_unknownUser_mfn34x
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.168 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

In [4]:
import pandas as pd
data = {
 "study_hours": [1,2,3,4,5,6,7,8],
 "attendance": [50,55,60,70,75,85,90,95],
 "internal_marks": [35,40,45,60,70,75,85,90],
 "result": ["Fail","Fail","Fail","Pass","Pass","Pass","Pass","Pass"]
}
df = pd.DataFrame(data)
df.to_csv("dataset.csv", index=False)
print("Dataset created successfully")
df

Dataset created successfully

   study_hours  attendance  internal_marks result
0            1          50              35   Fail
1            2          55              40   Fail
2            3          60              45   Fail
3            4          70              60   Pass
4            5          75              70   Pass
5            6          85              75   Pass
6            7          90              85   Pass
7            8          95              90   Pass

In [5]:
data = pd.read_csv("dataset.csv")
h2o_data = h2o.H2OFrame(data)
h2o_data

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  study_hours    attendance    internal_marks  result
-------------  ------------  ----------------  --------
            1            50                35  Fail
            2            55                40  Fail
            3            60                45  Fail
            4            70                60  Pass
            5            75                70  Pass
            6            85                75  Pass
            7            90                85  Pass
            8            95                90  Pass
[8 rows x 4 columns]

In [6]:
features = [
 "study_hours",
 "attendance",
 "internal_marks"
]
target = "result"

In [7]:
train, test = h2o_data.split_frame(
 ratios=[0.8],
 seed=42
)
print("Training Data:")
train.shape
print("Testing Data:")
test.shape

Training Data:
Testing Data:

(0, 4)

In [8]:
from h2o.automl import H2OAutoML
automl = H2OAutoML(
    max_models=10,
    seed=42,
    max_runtime_secs=120
)
automl.train(
    x=features,
    y=target,
    training_frame=train
)
print("AutoML Training Completed")

AutoML progress: |███
15:09:34.851: _min_rows param, The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 8.0.

████
15:09:41.132: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
15:09:41.133: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
15:09:41.137: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.

█████████████████
15:10:09.458: StackedEnsemble_BestOfFamily_1_AutoML_1_20260810_150927 [StackedEnsemble best_of_family_xglm (built with AUTO metalearner, using top model from each algorithm type)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).
15:10:09.588: StackedEnsemble_AllModels_1_AutoML_1_20260810_150927 [StackedEnsemble all_xglm (built with AUTO metalearner, using all AutoML models)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).

███████████████████████████████████████| (done) 100%
AutoML Training Completed

In [9]:
leaderboard = automl.leaderboard
leaderboard

model_id                                              auc    logloss     aucpr    mean_per_class_error       rmse         mse
-----------------------------------------------  --------  ---------  --------  ----------------------  ---------  ----------
GBM_5_AutoML_1_20260810_150927                   1         0          1                            0    0          0
XRT_1_AutoML_1_20260810_150927                   1         0.0525998  1                            0    0.0969211  0.00939371
DRF_1_AutoML_1_20260810_150927                   1         0.0557859  1                            0    0.127279   0.0162
GLM_1_AutoML_1_20260810_150927                   1         0.106802   1                            0    0.169975   0.0288914
GBM_grid_1_AutoML_1_20260810_150927_model_1      1         0.0186413  1                            0    0.0488917  0.0023904
DeepLearning_1_AutoML_1_20260810_150927          0.866667  2.44022    0.93834                      0.1  0.611404   0.373815
XGBoost_2_AutoML_1_20260810_150927               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_3_AutoML_1_20260810_150927               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_1_AutoML_1_20260810_150927               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_grid_1_AutoML_1_20260810_150927_model_1  0.3       0.703898   0.527391                     0.5  0.504221   0.254239
[10 rows x 7 columns]

In [10]:
best_model = automl.leader
best_model

Model Details
=============
H2OGradientBoostingEstimator : Gradient Boosting Machine
Model Key: GBM_5_AutoML_1_20260810_150927


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    467                467                         39558                  1            1            1             2             2             2

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.0
RMSE: 0.0
LogLoss: 0.0
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 1.0
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       1            1        0
max f2                       1            1        0
max f0point5                 1            1        0
max accuracy                 1            1        0
max precision                1            1        0
max recall                   1            1        0
max specificity              1            1        0
max absolute_mcc             1            1        0
max min_per_class_accuracy   1            1        0
max mean_per_class_accuracy  1            1        0
max tns                      1            3        0
max fns                      1            0        0
max fps                      1e-19        3        1
max tps                      1            5        0
max tnr                      1            1        0
max fnr                      1            0        0
max fpr                      1e-19        1        1
max tpr                      1            1        0

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 62.50 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score    cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  -------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.625                       1                  1.6     1.6                1                1        1                           1                   1               1                          60      60                 1
2        0.625                       0.8                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
3        0.625                       0.1                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
4        1                           1e-19              0       1                  0                1e-19    0.625                       0.625               0               1                          -100    0                  0

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.0
RMSE: 0.0
LogLoss: 0.0
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 1.0
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       1            1        0
max f2                       1            1        0
max f0point5                 1            1        0
max accuracy                 1            1        0
max precision                1            1        0
max recall                   1            1        0
max specificity              1            1        0
max absolute_mcc             1            1        0
max min_per_class_accuracy   1            1        0
max mean_per_class_accuracy  1            1        0
max tns                      1            3        0
max fns                      1            0        0
max fps                      3.26572e-18  3        3
max tps                      1            5        0
max tnr                      1            1        0
max fnr                      1            0        0
max fpr                      3.26572e-18  1        3
max tpr                      1            1        0

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 62.50 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score    cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  -------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.625                       1                  1.6     1.6                1                1        1                           1                   1               1                          60      60                 1
2        0.625                       0.8                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
3        0.625                       0.1                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
4        1                           0                  0       1                  0                0        0.625                       0.625               0               1                          -100    0                  0

Cross-Validation Metrics Summary:
                         mean    sd         cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ------  ---------  ------------  ------------  ------------  ------------  ------------
accuracy                 1.0     0.0        1.0           1.0           1.0           1.0           1.0
aic                      nan     0.0        nan           nan           nan           nan           nan
auc                      1.0     0.0        1.0           1.0           1.0           1.0           1.0
err                      0.0     0.0        0.0           0.0           0.0           0.0           0.0
err_count                0.0     0.0        0.0           0.0           0.0           0.0           0.0
f0point5                 1.0     0.0        1.0           1.0           1.0           1.0           1.0
f1                       1.0     0.0        1.0           1.0           1.0           1.0           1.0
f2                       1.0     0.0        1.0           1.0           1.0           1.0           1.0
lift_top_group           1.6     0.5477226  2.0           2.0           2.0           1.0           1.0
loglikelihood            nan     0.0        nan           nan           nan           nan           nan
---                      ---     ---        ---           ---           ---           ---           ---
mcc                      1.0     0.0        1.0           1.0           1.0           nan           nan
mean_per_class_accuracy  1.0     0.0        1.0           1.0           1.0           1.0           1.0
mean_per_class_error     0.0     0.0        0.0           0.0           0.0           0.0           0.0
mse                      0.0     0.0        0.0           0.0           0.0           0.0           0.0
pr_auc                   1.0     0.0        1.0           1.0           1.0           1.0           1.0
precision                1.0     0.0        1.0           1.0           1.0           1.0           1.0
r2                       1.0     0.0        1.0           1.0           1.0           nan           nan
recall                   1.0     0.0        1.0           1.0           1.0           1.0           1.0
rmse                     0.0     0.0        0.0           0.0           0.0           0.0           0.0
specificity              1.0     0.0        1.0           1.0           1.0           nan           nan
[22 rows x 8 columns]


Scoring History:
     timestamp            duration    number_of_trees    training_rmse          training_logloss      training_auc    training_pr_auc    training_lift    training_classification_error
---  -------------------  ----------  -----------------  ---------------------  --------------------  --------------  -----------------  ---------------  -------------------------------
     2026-08-10 15:09:55  11.073 sec  0.0                0.4841229182759271     0.6615632381579821    0.5             0.625              1.0              0.375
     2026-08-10 15:09:55  11.080 sec  5.0                0.28744098531349976    0.33179423348005704   1.0             1.0                1.6              0.0
     2026-08-10 15:09:55  11.086 sec  10.0               0.17281061705143097    0.1849078812159212    1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.094 sec  15.0               0.10433948954340246    0.10722099396976364   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.102 sec  20.0               0.06312498456781018    0.0633989639438956    1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.110 sec  25.0               0.038231183813121156   0.037886859196803555  1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.124 sec  30.0               0.023168343944167575   0.022778172607918094  1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.132 sec  35.0               0.014045061989749965   0.013743077471197568  1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.141 sec  40.0               0.00851612387776561    0.008309223611846687  1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.147 sec  45.0               0.0051643253470328165  0.005030166712740673  1.0             1.0                1.6              0.0
---  ---                  ---         ---                ---                    ---                   ---             ---                ---              ---
     2026-08-10 15:09:56  11.749 sec  425.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.757 sec  430.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.767 sec  435.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.778 sec  440.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.787 sec  445.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.799 sec  450.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.807 sec  455.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.815 sec  460.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.824 sec  465.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-10 15:09:56  11.831 sec  467.0              0.0                    0.0                   1.0             1.0                1.6              0.0
[95 rows x 10 columns]


Variable Importances:
variable        relative_importance    scaled_importance    percentage
--------------  ---------------------  -------------------  ------------
internal_marks  4.35537                1                    0.434352
study_hours     2.9362                 0.674155             0.292821
attendance      2.73571                0.628123             0.272827

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [11]:
train.shape

(8, 4)

In [12]:
test.shape

(0, 4)

In [13]:
import pandas as pd
import random
data = []
for i in range(100):
  study_hours = random.randint(1, 10)
  attendance = random.randint(50, 100)
  internal_marks = random.randint(35, 100)
  if (study_hours >= 5 and attendance >= 75 and internal_marks >= 60):
    result = "Pass"
  else:
    result = "Fail"
  data.append([
    study_hours,
    attendance,
    internal_marks,
    result
  ])
df = pd.DataFrame(
 data,
 columns=[
 "study_hours",
 "attendance",
 "internal_marks",
 "result"
 ]
)
df.to_csv("dataset.csv", index=False)
df.head()

   study_hours  attendance  internal_marks result
0            4          86              56   Fail
1            9          90              64   Pass
2            1          95              65   Fail
3            7          90              98   Pass
4            7          71              51   Fail

In [14]:
data = pd.read_csv("dataset.csv")
h2o_data = h2o.H2OFrame(data)
h2o_data["result"] = h2o_data["result"].asfactor()
h2o_data.head()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  study_hours    attendance    internal_marks  result
-------------  ------------  ----------------  --------
            4            86                56  Fail
            9            90                64  Pass
            1            95                65  Fail
            7            90                98  Pass
            7            71                51  Fail
           10            87                54  Fail
            2            77                63  Fail
            1            53                94  Fail
            7            96                72  Pass
            3            58                73  Fail
[10 rows x 4 columns]

In [15]:
train, test = h2o_data.split_frame(
 ratios=[0.8],
 seed=42
)
print("Train:", train.shape)
print("Test:", test.shape)

Train: (82, 4)
Test: (18, 4)

In [16]:
features = [
 "study_hours",
 "attendance",
 "internal_marks"
]
target = "result"
automl.train(
 x=features,
 y=target,
 training_frame=train
)

AutoML progress: |
15:09:34.851: _min_rows param, The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 8.0.
15:09:41.132: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
15:09:41.133: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
15:09:41.137: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
15:10:09.458: StackedEnsemble_BestOfFamily_1_AutoML_1_20260810_150927 [StackedEnsemble best_of_family_xglm (built with AUTO metalearner, using top model from each algorithm type)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).
15:10:09.588: StackedEnsemble_AllModels_1_AutoML_1_20260810_150927 [StackedEnsemble all_xglm (built with AUTO metalearner, using all AutoML models)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).
15:11:48.203: New models will be added to existing leaderboard AutoML_1_20260810_150927@@result (leaderboard frame=null) with already 10 models.

█
15:11:51.678: _min_rows param, The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 82.0.

██████████████████████
15:12:32.488: StackedEnsemble_BestOfFamily_2_AutoML_2_20260810_151148 [StackedEnsemble best_of_family_xglm (built with AUTO metalearner, using top model from each algorithm type)] failed: water.exceptions.H2OIllegalArgumentException: Base models are inconsistent: they use different size (number of rows) training frames. Found: 82 (StackedEnsemble) and 8 (model DRF_1_AutoML_1_20260810_150927).
15:12:32.501: StackedEnsemble_AllModels_2_AutoML_2_20260810_151148 [StackedEnsemble all_xglm (built with AUTO metalearner, using all AutoML models)] failed: water.exceptions.H2OIllegalArgumentException: Base models are inconsistent: they use different size (number of rows) training frames. Found: 82 (StackedEnsemble) and 8 (model DRF_1_AutoML_1_20260810_150927).

████████████████████████████████████████| (done) 100%

Model Details
=============
H2ORandomForestEstimator : Distributed Random Forest
Model Key: XRT_1_AutoML_1_20260810_150927


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    41                 41                          3457                   1            2            1.04878       2             3             2.04878

ModelMetricsBinomial: drf
** Reported on train data. **

MSE: 0.0068633572505695855
RMSE: 0.08284538158865336
LogLoss: 0.03935377554634912
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 1.0
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       1            1        0
max f2                       1            1        0
max f0point5                 1            1        0
max accuracy                 1            1        0
max precision                1            1        0
max recall                   1            1        0
max specificity              1            1        0
max absolute_mcc             1            1        0
max min_per_class_accuracy   1            1        0
max mean_per_class_accuracy  1            1        0
max tns                      1            3        0
max fns                      1            0        0
max fps                      0.0131579    3        3
max tps                      1            5        0
max tnr                      1            1        0
max fnr                      1            0        0
max fpr                      0.0131579    1        3
max tpr                      1            1        0

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 66.03 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.625                       1                  1.6     1.6                1                1          1                           1                   1               1                          60      60                 1
2        0.625                       0.846154           0       1.6                0                0          1                           1                   0               1                          -100    60                 1
3        0.625                       0.307692           0       1.6                0                0          1                           1                   0               1                          -100    60                 1
4        0.75                        0.115385           0       1.33333            0                0.230769   0.833333                    0.871795            0               1                          -100    33.3333            0.666667
5        0.875                       0.0308704          0       1.14286            0                0.0384615  0.714286                    0.752747            0               1                          -100    14.2857            0.333333
6        1                           0.0131579          0       1                  0                0.0131579  0.625                       0.660299            0               1                          -100    0                  0

ModelMetricsBinomial: drf
** Reported on cross-validation data. **

MSE: 0.009393707409055053
RMSE: 0.09692114015556695
LogLoss: 0.05259981326457274
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9714285714285714
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       0.971429     1        1
max f2                       0.971429     1        1
max f0point5                 0.971429     1        1
max accuracy                 0.971429     1        1
max precision                1            1        0
max recall                   0.971429     1        1
max specificity              1            1        0
max absolute_mcc             0.971429     1        1
max min_per_class_accuracy   0.971429     1        1
max mean_per_class_accuracy  0.971429     1        1
max tns                      1            3        0
max fns                      1            1        0
max fps                      0.0366667    3        4
max tps                      0.971429     5        1
max tnr                      1            1        0
max fnr                      1            0.2      0
max fpr                      0.0366667    1        4
max tpr                      0.971429     1        1

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 66.48 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.5                         1                  1.6     1.6                1                1          1                           1                   0.8             0.8                        60      60                 0.8
2        0.5                         0.985714           0       1.6                0                0          1                           1                   0               0.8                        -100    60                 0.8
3        0.625                       0.830476           1.6     1.6                1                0.971429   1                           0.994286            0.2             1                          60      60                 1
4        0.625                       0.337143           0       1.6                0                0          1                           0.994286            0               1                          -100    60                 1
5        0.75                        0.132667           0       1.33333            0                0.266667   0.833333                    0.873016            0               1                          -100    33.3333            0.666667
6        0.875                       0.0413333          0       1.14286            0                0.0433333  0.714286                    0.75449             0               1                          -100    14.2857            0.333333
7        1                           0.0366667          0       1                  0                0.0366667  0.625                       0.664762            0               1                          -100    0                  0

Cross-Validation Metrics Summary:
                         mean          sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid     cv_5_valid
-----------------------  ------------  -----------  ------------  ------------  ------------  -------------  ------------
accuracy                 1.0           0.0          1.0           1.0           1.0           1.0            1.0
aic                      nan           0.0          nan           nan           nan           nan            nan
auc                      1.0           0.0          1.0           1.0           1.0           1.0            1.0
err                      0.0           0.0          0.0           0.0           0.0           0.0            0.0
err_count                0.0           0.0          0.0           0.0           0.0           0.0            0.0
f0point5                 1.0           0.0          1.0           1.0           1.0           1.0            1.0
f1                       1.0           0.0          1.0           1.0           1.0           1.0            1.0
f2                       1.0           0.0          1.0           1.0           1.0           1.0            1.0
lift_top_group           1.6           0.5477226    2.0           2.0           2.0           1.0            1.0
loglikelihood            nan           0.0          nan           nan           nan           nan            nan
---                      ---           ---          ---           ---           ---           ---            ---
mcc                      1.0           0.0          1.0           1.0           1.0           nan            nan
mean_per_class_accuracy  1.0           0.0          1.0           1.0           1.0           1.0            1.0
mean_per_class_error     0.0           0.0          0.0           0.0           0.0           0.0            0.0
mse                      0.0075965985  0.015633743  0.0006722222  0.0009388888  0.035555556   0.00081632653  0.0
pr_auc                   1.0           0.0          1.0           1.0           1.0           1.0            1.0
precision                1.0           0.0          1.0           1.0           1.0           1.0            1.0
r2                       -inf          nan          0.9973111     0.99624443    0.8577778     -inf           nan
recall                   1.0           0.0          1.0           1.0           1.0           1.0            1.0
rmse                     0.054740354   0.07582951   0.025927247   0.030641293   0.18856181    0.028571429    0.0
specificity              1.0           0.0          1.0           1.0           1.0           nan            nan
[22 rows x 8 columns]


Scoring History:
    timestamp            duration    number_of_trees    training_rmse    training_logloss    training_auc    training_pr_auc    training_lift    training_classification_error
--  -------------------  ----------  -----------------  ---------------  ------------------  --------------  -----------------  ---------------  -------------------------------
    2026-08-10 15:09:44  0.771 sec   0                  nan              nan                 nan             nan                nan              nan
    2026-08-10 15:09:44  0.783 sec   5                  0.0613317        0.0367571           1               1                  1.6              0
    2026-08-10 15:09:44  0.798 sec   10                 0.0246           0.0134076           1               1                  1.6              0
    2026-08-10 15:09:44  0.807 sec   15                 0.0184142        0.00928854          1               1                  1.6              0
    2026-08-10 15:09:44  0.814 sec   20                 0.142211         0.0712728           1               1                  1.6              0
    2026-08-10 15:09:44  0.828 sec   25                 0.133386         0.0659281           1               1                  1.6              0
    2026-08-10 15:09:44  0.843 sec   30                 0.106803         0.0506538           1               1                  1.6              0
    2026-08-10 15:09:44  0.881 sec   35                 0.0821984        0.0376159           1               1                  1.6              0
    2026-08-10 15:09:44  0.889 sec   40                 0.0828454        0.0393538           1               1                  1.6              0
    2026-08-10 15:09:44  0.894 sec   41                 0.0828454        0.0393538           1               1                  1.6              0

Variable Importances:
variable        relative_importance    scaled_importance    percentage
--------------  ---------------------  -------------------  ------------
internal_marks  28.125                 1                    0.384791
attendance      26.75                  0.951111             0.365979
study_hours     18.2167                0.647704             0.24923

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [17]:
best_model = automl.leader
performance = best_model.model_performance(test)
performance

ModelMetricsBinomial: drf
** Reported on test data. **

MSE: 0.36591975675854316
RMSE: 0.6049130158614072
LogLoss: 8.055382569943474
Mean Per-Class Error: 0.18181818181818182
AUC: 0.8181818181818182
AUCPR: 0.6363636363636364
Gini: 0.6363636363636365

Confusion Matrix (Act/Pred) for max f1 @ threshold = 1.0
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ----------
Fail   7       4       0.3636   (4.0/11.0)
Pass   0       7       0        (0.0/7.0)
Total  7       11      0.2222   (4.0/18.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       1            0.777778  0
max f2                       1            0.897436  0
max f0point5                 1            0.686275  0
max accuracy                 1            0.777778  0
max precision                1            0.636364  0
max recall                   1            1         0
max specificity              1            0.636364  0
max absolute_mcc             1            0.636364  0
max min_per_class_accuracy   1            0.636364  0
max mean_per_class_accuracy  1            0.818182  0
max tns                      1            7         0
max fns                      1            0         0
max fps                      0.134146     11        7
max tps                      1            7         0
max tnr                      1            0.636364  0
max fnr                      1            0         0
max fpr                      0.134146     1         7
max tpr                      1            1         0

Gains/Lift Table: Avg response rate: 38.89 %, avg score: 83.20 %
group    cumulative_data_fraction    lower_threshold    lift     cumulative_lift    response_rate    score     cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain     cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  -------  -----------------  ---------------  --------  --------------------------  ------------------  --------------  -------------------------  -------  -----------------  --------------------
1        0.611111                    1                  1.63636  1.63636            0.636364         1         0.636364                    1                   1               1                          63.6364  63.6364            0.636364
2        0.611111                    0.973171           0        1.63636            0                0         0.636364                    1                   0               1                          -100     63.6364            0.636364
3        0.666667                    0.767073           0        1.5                0                0.865854  0.583333                    0.988821            0               1                          -100     50                 0.545455
4        0.777778                    0.612195           0        1.28571            0                0.695122  0.5                         0.946864            0               1                          -100     28.5714            0.363636
5        0.888889                    0.496341           0        1.125              0                0.54878   0.4375                      0.897104            0               1                          -100     12.5               0.181818
6        1                           0.134146           0        1                  0                0.310976  0.388889                    0.831978            0               1                          -100     0                  0

In [18]:
accuracy = performance.accuracy()[0][1]
precision = performance.precision()[0][1]
recall = performance.recall()[0][1]
f1_score = performance.F1()[0][1]
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall :", recall)
print("F1 Score :", f1_score)

Accuracy : 0.7777777777777778
Precision: 0.6363636363636364
Recall : 1.0
F1 Score : 0.7777777777777778

In [19]:
import dagshub
import mlflow
dagshub.init(
 repo_owner="charybhanuprasad07",
 repo_name="mlops-shared-repo",
 mlflow=True
)
mlflow.set_experiment("H2O_AutoML_Experiment")

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=fecf25a1-e28c-4a6a-b0bf-1a7a3d1d81cf&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=71590964bcbfd113390099830fcbc5e2b533886130f1c91d297716cbdf82ef9e

Accessing as charybhanuprasad07

Initialized MLflow to track repo "charybhanuprasad07/mlops-shared-repo"

Repository charybhanuprasad07/mlops-shared-repo initialized!

<Experiment: artifact_location='mlflow-artifacts:/be917ca4420742258ced7af617c9fee3', creation_time=1786249493245, effective_trace_archival_retention=None, experiment_id='2', last_update_time=1786249493245, lifecycle_stage='active', name='H2O_AutoML_Experiment', tags={}, trace_location=None, workspace='default'>

In [20]:
try:
    with mlflow.start_run():
        mlflow.log_param(
            "algorithm",
            "H2O AutoML"
        )
        mlflow.log_param(
            "max_models",
            10
        )
        mlflow.log_param(
            "dataset",
            "student_performance"
        )

        mlflow.log_metric(
            "accuracy",
            accuracy
        )
        mlflow.log_metric(
            "precision",
            precision
        )
        mlflow.log_metric(
            "recall",
            recall
        )
        mlflow.log_metric(
            "f1_score",
            f1_score
        )
    print("MLflow logging completed")
except Exception as e:
    print(f"An error occurred during MLflow logging: {e}")

🏃 View run dapper-roo-914 at: https://dagshub.com/charybhanuprasad07/mlops-shared-repo.mlflow/#/experiments/2/runs/5a96c1d3c13c4afab0791af5c6cd80b6
🧪 View experiment at: https://dagshub.com/charybhanuprasad07/mlops-shared-repo.mlflow/#/experiments/2
MLflow logging completed

In [21]:
model_path = h2o.save_model(
 model=best_model,
 path="/content/automl_model"
)
print(model_path)

/content/automl_model/XRT_1_AutoML_1_20260810_150927

In [22]:
new_data = h2o.H2OFrame(
 {
 "study_hours":[8],
 "attendance":[95],
 "internal_marks":[90]
 }
)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [23]:
prediction = best_model.predict(new_data)
prediction

drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict      Fail    Pass
---------  ------  ------
Pass            0       1
[1 row x 3 columns]

In [24]:
results = pd.DataFrame(
 {
 "Model":["H2O AutoML Best Model"],
 "Accuracy":[accuracy],
 "Precision":[precision],
 "Recall":[recall],
 "F1 Score":[f1_score]
 }
)
results.to_csv(
 "automl_results.csv",
 index=False
)
results

                   Model  Accuracy  Precision  Recall  F1 Score
0  H2O AutoML Best Model  0.777778   0.636364     1.0  0.777778

In [25]:
!ls -la

total 28
drwxr-xr-x 1 root root 4096 Aug 10 15:15 .
drwxr-xr-x 1 root root 4096 Aug 10 14:57 ..
drwxr-xr-x 2 root root 4096 Aug 10 15:15 automl_model
-rw-r--r-- 1 root root  124 Aug 10 15:15 automl_results.csv
drwxr-xr-x 4 root root 4096 Jun  4 13:32 .config
-rw-r--r-- 1 root root 1356 Aug 10 15:11 dataset.csv
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data

In [26]:
from getpass import getpass
token = getpass("Enter DagsHub Token: ")

Enter DagsHub Token: ··········

In [32]:
!git clone https://dagshub.com/charybhanuprasad07/mlops-shared-repo.git

Cloning into 'mlops-shared-repo'...
fatal: could not read Username for 'https://dagshub.com': No such device or address

In [33]:
%cd /content/mlops-shared-repo
!ls -la

[Errno 2] No such file or directory: '/content/mlops-shared-repo'
/content
total 28
drwxr-xr-x 1 root root 4096 Aug 10 15:18 .
drwxr-xr-x 1 root root 4096 Aug 10 14:57 ..
drwxr-xr-x 2 root root 4096 Aug 10 15:15 automl_model
-rw-r--r-- 1 root root   85 Aug 10 15:16 automl_results.csv
drwxr-xr-x 4 root root 4096 Jun  4 13:32 .config
-rw-r--r-- 1 root root 1356 Aug 10 15:11 dataset.csv
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data

In [34]:
import pandas as pd
results = pd.DataFrame(
 {
 "Model": ["H2O AutoML Best Model"],
 "Accuracy": [0.888888],
 "Precision": [0.6],
 "Recall": [1.0],
 "F1 Score": [0.75]
 }
)
results.to_csv(
 "automl_results.csv",
 index=False
)
results

                   Model  Accuracy  Precision  Recall  F1 Score
0  H2O AutoML Best Model  0.888888        0.6     1.0      0.75

In [35]:
!ls -la

total 28
drwxr-xr-x 1 root root 4096 Aug 10 15:18 .
drwxr-xr-x 1 root root 4096 Aug 10 14:57 ..
drwxr-xr-x 2 root root 4096 Aug 10 15:15 automl_model
-rw-r--r-- 1 root root   85 Aug 10 15:18 automl_results.csv
drwxr-xr-x 4 root root 4096 Jun  4 13:32 .config
-rw-r--r-- 1 root root 1356 Aug 10 15:11 dataset.csv
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data

In [44]:
import os
from getpass import getpass

# Explicitly define username and repo_name to ensure they are correct string literals
username = "charybhanuprasad07"
repo_name = "mlops-shared-repo"

# Re-prompt for the token to ensure it's correctly captured as a string
token = getpass("Please re-enter your DagsHub Token: ")

# Ensure the target directory for cloning is clean
repo_dir = repo_name # Use repo_name for consistency
if os.path.exists(repo_dir):
    !rm -rf {repo_dir}

# Construct the authenticated repository URL
repo_url = f"https://{username}:{token}@dagshub.com/{username}/{repo_name}.git"

# Clone the repository
!git clone {repo_url}

# Change the current working directory to the cloned repository
%cd {repo_dir}

# Now, perform the git add operation
!git add .

Please re-enter your DagsHub Token: ··········
Cloning into 'mlops-shared-repo'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (4/4), done.
/content/mlops-shared-repo

In [45]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [47]:
!git config --global user.name "chary"
!git config --global user.email "charybhanuprasad07@gmail.com"

In [50]:
# Move the generated files and directories into the repository
!mv /content/automl_results.csv ./automl_results.csv
!mv /content/automl_model ./automl_model

# Now, add and commit the changes
!git add .
!git commit -m "Completed H2O AutoML MLOps experiment"

[main 34b567e] Completed H2O AutoML MLOps experiment
 2 files changed, 53 insertions(+)
 create mode 100644 automl_model/XRT_1_AutoML_1_20260810_150927
 create mode 100644 automl_results.csv

In [56]:
# Fetch the latest changes from the remote to update local tracking branches
!git fetch origin

# Pull any remote changes and merge them into the local main branch
!git pull origin main

# Display the commit history for local main branch
print("\n--- Local main branch log ---")
!git log --oneline main

# Display the commit history for remote-tracking origin/main branch
print("\n--- Remote origin/main log ---")
!git log --oneline origin/main

# Check status to confirm local branch is ahead after the pull (should be 'up to date' if commit 34b567e is on remote)
print("\n--- Git Status ---")
!git status

# Attempt to push the committed changes to the remote repository
# This command will again report 'Everything up-to-date' if the commit is already on remote.
print("\n--- Git Push Attempt ---")
!git push origin main

From https://dagshub.com/charybhanuprasad07/mlops-shared-repo
 * branch            main       -> FETCH_HEAD
Already up to date.

--- Local main branch log ---
34b567e (HEAD -> main, origin/main, origin/HEAD) Completed H2O AutoML MLOps experiment
b11f5b9 Added MLflow experiment and outputs(updated)

--- Remote origin/main log ---
34b567e (HEAD -> main, origin/main, origin/HEAD) Completed H2O AutoML MLOps experiment
b11f5b9 Added MLflow experiment and outputs(updated)

--- Git Status ---
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

--- Git Push Attempt ---
Everything up-to-date