In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Create project folder
!mkdir DVC_Project

In [ ]:
# Pushing the project files
%cd DVC_Project

/content/DVC_Project

In [ ]:
!pip install dvc

Collecting dvc
  Downloading dvc-3.67.1-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (26.1.0)
Collecting celery (from dvc)
  Downloading celery-5.6.3-py3-none-any.whl.metadata (23 kB)
Collecting colorama>=0.3.9 (from dvc)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting configobj>=5.0.9 (from dvc)
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.9.0)
Collecting dpath<3,>=2.1.0 (from dvc)
  Downloading dpath-2.2.0-py3-none-any.whl.metadata (15 kB)
Collecting dulwich (from dvc)
  Downloading dulwich-1.2.12-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.0 kB)
Collecting dvc-data<3.19.0,>=3.18.2 (from dvc)
  Downloading dvc_data-3.18.3-py3-none-any.whl.metadata (4.9 kB)
Collecting dvc-http>=2.29.0 (from dvc)
  Downloading dvc_http-2.32.0-py3-none-any.whl.metadata (1.3 kB)
Collecting dvc-objects (from dvc)
  Downloading dvc_objects-5.2.0-py3-none-any.whl.metadata (3.9 kB)
Collecting dvc-render<2,>=1.0.1 (from dvc)
  Downloading dvc_render-1.0.2-py3-none-any.whl.metadata (5.4 kB)
Collecting dvc-studio-client<1,>=0.21 (from dvc)
  Downloading dvc_studio_client-0.23.0-py3-none-any.whl.metadata (4.4 kB)
Collecting dvc-task<1,>=0.3.0 (from dvc)
  Downloading dvc_task-0.40.2-py3-none-any.whl.metadata (10.0 kB)
Collecting flatten-dict<1,>=0.4.1 (from dvc)
  Downloading flatten_dict-0.5.0-py3-none-any.whl.metadata (8.9 kB)
Collecting flufl.lock<10,>=8.1.0 (from dvc)
  Downloading flufl_lock-9.1.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2025.3.0)
Collecting funcy>=1.14 (from dvc)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting grandalf<1,>=0.7 (from dvc)
  Downloading grandalf-0.8-py3-none-any.whl.metadata (1.7 kB)
Collecting gto<2,>=1.6.0 (from dvc)
  Downloading gto-1.10.1-py3-none-any.whl.metadata (4.8 kB)
Collecting hydra-core>=1.1 (from dvc)
  Downloading hydra_core-1.3.4-py3-none-any.whl.metadata (5.7 kB)
Collecting iterative-telemetry>=0.0.7 (from dvc)
  Downloading iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting kombu (from dvc)
  Downloading kombu-5.6.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.6.1)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (from dvc) (2.3.1)
Requirement already satisfied: packaging>=19 in /usr/local/lib/python3.12/dist-packages (from dvc) (26.2)
Collecting pathspec<2,>=0.10.3 (from dvc)
  Downloading pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.10.0)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.12/dist-packages (from dvc) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.0.1)
Collecting pygtrie>=2.3.2 (from dvc)
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: pyparsing>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.3.2)
Requirement already satisfied: requests>=2.22 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.32.4)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.12/dist-packages (from dvc) (13.9.4)
Collecting ruamel.yaml>=0.17.11 (from dvc)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Collecting scmrepo<4,>=3.5.2 (from dvc)
  Downloading scmrepo-3.6.2-py3-none-any.whl.metadata (4.8 kB)
Collecting shortuuid>=0.5 (from dvc)
  Downloading shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting shtab<2,>=1.3.4 (from dvc)
  Downloading shtab-1.9.2-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.9.0)
Requirement already satisfied: tomlkit>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.14.0)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.67.3)
Collecting voluptuous>=0.11.7 (from dvc)
  Downloading voluptuous-0.16.0-py3-none-any.whl.metadata (20 kB)
Collecting zc.lockfile>=1.2.1 (from dvc)
  Downloading zc_lockfile-4.0-py3-none-any.whl.metadata (6.6 kB)
Collecting dictdiffer>=0.8.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading dictdiffer-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Collecting diskcache>=5.2.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting sqltrie<1,>=0.11.0 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading sqltrie-0.11.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.11.9)
Collecting aiohttp-retry>=2.5.0 (from dvc-http>=2.29.0->dvc)
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Collecting billiard<5.0,>=4.2.1 (from celery->dvc)
  Downloading billiard-4.2.4-py3-none-any.whl.metadata (4.8 kB)
Collecting vine<6.0,>=5.1.0 (from celery->dvc)
  Downloading vine-5.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: click<9.0,>=8.1.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (8.4.2)
Collecting click-didyoumean>=0.3.0 (from celery->dvc)
  Downloading click_didyoumean-0.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting click-repl>=0.2.0 (from celery->dvc)
  Downloading click_repl-0.3.0-py3-none-any.whl.metadata (3.6 kB)
Collecting click-plugins>=1.1.1 (from celery->dvc)
  Downloading click_plugins-1.1.1.2-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (2.9.0.post0)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (5.4.4)
Requirement already satisfied: atpublic in /usr/local/lib/python3.12/dist-packages (from flufl.lock<10,>=8.1.0->dvc) (5.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (2.13.4)
Collecting pydantic-settings>=2 (from gto<2,>=1.6.0->dvc)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Collecting semver>=2.13.0 (from gto<2,>=1.6.0->dvc)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.1->dvc) (4.9.3)
Collecting appdirs (from iterative-telemetry>=0.0.7->dvc)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.7->dvc) (3.29.7)
Collecting amqp<6.0.0,>=5.1.1 (from kombu->dvc)
  Downloading amqp-5.3.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: tzdata>=2025.2 in /usr/local/lib/python3.12/dist-packages (from kombu->dvc) (2026.3)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from omegaconf->dvc) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (2.20.0)
Requirement already satisfied: gitpython>3 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (3.1.51)
Requirement already satisfied: pygit2>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (1.19.3)
Collecting asyncssh<3,>=2.13.1 (from scmrepo<4,>=3.5.2->dvc)
  Downloading asyncssh-2.24.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from zc.lockfile>=1.2.1->dvc) (75.2.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (3.14.1)
Requirement already satisfied: cryptography>=48.0.1 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (49.0.0)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (4.16.0)
Requirement already satisfied: prompt-toolkit>=3.0.36 in /usr/local/lib/python3.12/dist-packages (from click-repl>=0.2.0->celery->dvc) (3.0.52)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython>3->scmrepo<4,>=3.5.2->dvc) (4.0.12)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2->gto<2,>=1.6.0->dvc) (1.2.2)
Requirement already satisfied: cffi>=2.0 in /usr/local/lib/python3.12/dist-packages (from pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (2.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->celery->dvc) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.24.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0->pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc) (5.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.8.2)
Downloading dvc-3.67.1-py3-none-any.whl (470 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.1/470.1 kB 9.9 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading configobj-5.0.9-py2.py3-none-any.whl (35 kB)
Downloading dpath-2.2.0-py3-none-any.whl (17 kB)
Downloading dvc_data-3.18.3-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 5.6 MB/s eta 0:00:00
Downloading dvc_http-2.32.0-py3-none-any.whl (12 kB)
Downloading dvc_objects-5.2.0-py3-none-any.whl (33 kB)
Downloading dvc_render-1.0.2-py3-none-any.whl (22 kB)
Downloading dvc_studio_client-0.23.0-py3-none-any.whl (16 kB)
Downloading dvc_task-0.40.2-py3-none-any.whl (21 kB)
Downloading celery-5.6.3-py3-none-any.whl (451 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 451.2/451.2 kB 29.2 MB/s eta 0:00:00
Downloading flatten_dict-0.5.0-py3-none-any.whl (9.9 kB)
Downloading flufl_lock-9.1.0-py3-none-any.whl (11 kB)
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Downloading grandalf-0.8-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 3.2 MB/s eta 0:00:00
Downloading gto-1.10.1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 3.6 MB/s eta 0:00:00
Downloading hydra_core-1.3.4-py3-none-any.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.5/155.5 kB 13.2 MB/s eta 0:00:00
Downloading iterative_telemetry-0.0.10-py3-none-any.whl (10 kB)
Downloading kombu-5.6.2-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.2/214.2 kB 18.3 MB/s eta 0:00:00
Downloading vine-5.1.0-py3-none-any.whl (9.6 kB)
Downloading pathspec-1.1.1-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.6 MB/s eta 0:00:00
Downloading pygtrie-2.5.0-py3-none-any.whl (25 kB)
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 10.9 MB/s eta 0:00:00
Downloading scmrepo-3.6.2-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.2/74.2 kB 7.3 MB/s eta 0:00:00
Downloading dulwich-1.2.12-cp312-cp312-manylinux_2_28_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 53.0 MB/s eta 0:00:00
Downloading shortuuid-1.0.13-py3-none-any.whl (10 kB)
Downloading shtab-1.9.2-py3-none-any.whl (15 kB)
Downloading voluptuous-0.16.0-py3-none-any.whl (31 kB)
Downloading zc_lockfile-4.0-py3-none-any.whl (9.1 kB)
Downloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)
Downloading amqp-5.3.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.9 MB/s eta 0:00:00
Downloading asyncssh-2.24.0-py3-none-any.whl (381 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.2/381.2 kB 27.4 MB/s eta 0:00:00
Downloading billiard-4.2.4-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.1/87.1 kB 7.0 MB/s eta 0:00:00
Downloading click_didyoumean-0.3.1-py3-none-any.whl (3.6 kB)
Downloading click_plugins-1.1.1.2-py2.py3-none-any.whl (11 kB)
Downloading click_repl-0.3.0-py3-none-any.whl (10 kB)
Downloading dictdiffer-0.10.0-py3-none-any.whl (16 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 3.8 MB/s eta 0:00:00
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.4 MB/s eta 0:00:00
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading sqltrie-0.11.2-py3-none-any.whl (17 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: pygtrie, funcy, appdirs, zc.lockfile, voluptuous, vine, sqltrie, shtab, shortuuid, semver, ruamel.yaml, pathspec, grandalf, flufl.lock, flatten-dict, dvc-render, dvc-objects, dulwich, dpath, diskcache, dictdiffer, configobj, colorama, click-plugins, click-didyoumean, billiard, iterative-telemetry, hydra-core, dvc-studio-client, dvc-data, click-repl, amqp, pydantic-settings, kombu, asyncssh, aiohttp-retry, scmrepo, dvc-http, celery, gto, dvc-task, dvc
Successfully installed aiohttp-retry-2.9.1 amqp-5.3.1 appdirs-1.4.4 asyncssh-2.24.0 billiard-4.2.4 celery-5.6.3 click-didyoumean-0.3.1 click-plugins-1.1.1.2 click-repl-0.3.0 colorama-0.4.6 configobj-5.0.9 dictdiffer-0.10.0 diskcache-5.6.3 dpath-2.2.0 dulwich-1.2.12 dvc-3.67.1 dvc-data-3.18.3 dvc-http-2.32.0 dvc-objects-5.2.0 dvc-render-1.0.2 dvc-studio-client-0.23.0 dvc-task-0.40.2 flatten-dict-0.5.0 flufl.lock-9.1.0 funcy-2.0 grandalf-0.8 gto-1.10.1 hydra-core-1.3.4 iterative-telemetry-0.0.10 kombu-5.6.2 pathspec-1.1.1 pydantic-settings-2.14.2 pygtrie-2.5.0 ruamel.yaml-0.19.1 scmrepo-3.6.2 semver-3.0.4 shortuuid-1.0.13 shtab-1.9.2 sqltrie-0.11.2 vine-5.1.0 voluptuous-0.16.0 zc.lockfile-4.0

In [ ]:
# Step 6: Initialize Git
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/DVC_Project/.git/

In [ ]:
# Step 7: Iitialize DVC
!dvc init

Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/treeverse/dvc>

In [ ]:
# Creat Dataset
import pandas as pd
data = {
 "Student":["Ravi","Priya","Anu","Rahul"],
 "Marks":[90,85,78,95]
}

df = pd.DataFrame(data)
df.to_csv("student.csv",index = False)
df.head()

  Student  Marks
0    Ravi     90
1   Priya     85
2     Anu     78
3   Rahul     95

In [ ]:
# Step 9: Add Dataset into DVC
!dvc add student.csv

⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s]
Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

Checking out /content/DVC_Project/student.csv:   0% 0/1 [00:00<?, ?files/s]
  0% 0/1 [00:00<?, ?files/s{'info': ''}]
Adding...: 100% 1/1 [00:00<00:00,  6.69file/s{'info': ''}]

To track the changes with git, run:

	git add student.csv.dvc .gitignore

To enable auto staging, run:

	dvc config core.autostage true

In [ ]:
# Step 10:
!ls #---------> what all the things is present in the drive

student.csv  student.csv.dvc

In [ ]:
# Step 11: Commit Version 1
!git config --global user.name "chary"
!git config --global user.email "charybhanuprasad07@gmail.com"

In [ ]:
!git config --global --list

user.name=chary
user.email=charybhanuprasad07@gmail.com

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%cd /content/drive/MyDrive
!ls

/content/drive/MyDrive
'1.2 ( St.Got Finals ).gdoc'
 24AD2204-ML-Workbook.gdoc
'27Introduction To files Create, Read.gslides'
'28 Append  Defete from file.gslides'
'3.1 ( Musical Jam Nights ).gdoc'
'3.2 ( Cricket ).gdoc'
'5.1 ( Mental Health ).gdoc'
 5_6080418538483357247.gdoc
 5.Iteration.gslides
 7001040005751_ProvisionalCertificate.gdoc
'7 .Strings.gslides'
'aggregation and composition.gdoc'
 AI_NOTES.gdoc
'Arrays in java.gdoc'
"Bhanu's Resume.pdf"
'Cases-Kasus-- Flow of actions betwe.gdoc'
'Cases-Kasus-- Flow of actions betwe.txt'
'CASE STUDY -Document-Finalized (1).gdoc'
'CASE STUDY -Document-Finalized.gdoc'
'CASE STUDY -Document.gdoc'
'CHRISTAMAS CO2.gdoc'
'CIAS NOTES.gdoc'
 CIS_CO1_SESSION01.gslides
'CO1 CO2 questions.gdoc'
'co-1 sil report.gdoc'
'CO2 Questions.gdoc'
'CO-2 REPORT.gdoc'
'CO-2 SIL REPORT.gdoc'
'CO3and 4 ML .gdoc'
'CO3and 4 ML .pdf'
'CO3_NLP_BEALES METHOD (1).pdf'
'CO_3 NLP_WOLFES METHOD _KKT CONDITIONSpdf.pdf'
'CO3 PPT.gslides'
'CO3 SIL REPORT.gdoc'
 CO_4_Lecture_25_GPIO_Programming_ESP32.gslides
 CO_4_Lecture_27_LCD.gslides
'CO-4 REPORT.gdoc'
'co-4 sil report.gdoc'
'CO-5 REPORT.gdoc'
'CO-5 REPORTS hemi .gdoc'
'co-5 sil reports.gdoc'
'Colab Notebooks'
'Copy of College Pastel Notes Green variant.gslides'
'Copy of Private University by Slidesgo.gslides'
'COVID_19 INDIA1.gsheet'
'Data structures with Python CO1C02.gdoc'
'DBMS Notes.gdoc'
'die Zahlen (2).gdoc'
'DSV Notes.gdoc'
'DSV Project Documentation Format.gdoc'
'DTI AY 2023-24-WIP-1 Even Sem.gslides'
'DTI Project Report 2024-25 Odd Sem Template.gdoc'
'DTW-CO3 & CO4 Document.gdoc'
'DTW CO 4.gdoc'
'dtw lab manual.gdoc'
'DTW_Lab manual.gdoc'
'DTW PROJECT'
'Employee Payslip _ IFMIS(18).gdoc'
'Experiments (1).gdoc'
 Experiments.gdoc
'FEDF Project Documentation sample format.gdoc'
'FILM MAKING CO3.gdoc'
'Foundations of AI-Enabled Edge Computing.gdoc'
'FRONT END  DEVELOPMENT FRAME WORK ASSIGNMENT .gdoc'
'FSAD project abstract.gdoc'
'FSAD Theory Short Notes .gdoc'
'Full Stack Devlopment @ IIT HYDERABAD.gdoc'
 g1.PNG
 g2.PNG
 g3.PNG
'GEOMETRIC PROGRAMMING.pdf'
'Google AI Studio'
'Google Finance Investment Tracker.gsheet'
'Group15_OS_Abstract (1).gdoc'
'Indian mathematicians and statisticians.gslides'
'LAB BOOK -FOUNDATIONS OF AI-ENABLED EDGE COMPUTING FINAL.gdoc'
'LIST OF LAB PROGS.gdoc'
'ML_Project Documentation (3).gdoc'
'MO_CO4_INFINITE DIMENTIONAL OPTIMIZATION.pdf'
'MY AI Notes .gdoc'
 New-675-GB-Graphic-Bundle-v4mujd.pdf
 OOP-R_CO1_Assignment_1.gdoc
'OOPS Notes.gdoc'
'Operating system - S6.gdoc'
'OS abstract format.gdoc'
'OS hackthon abstract format (1).gdoc'
'OS hackthon abstract format.gdoc'
'os _s6-Registeted students listcsv.gdoc'
 pdf_62529861_1708432155549.gdoc
'project abstract .gdoc'
'PSO&ACO_EXAMPLES.pdf'
 Resume.gdoc
'Review1 form and students can take printout.gdoc'
 S18_DC_Motor.gslides
 S19_Servo_Motor.gslides
 S20_Stepper_Motor.gslides
 S21_Motor_Driver_Circuit.gslides
 S23_Opto_Couplers.gslides
'sample ppt format(1).gslides'
'Saved from Chrome'
'self awarness.gdoc'
'Session11 Sets.gslides'
'Session12 Tuple.gslides'
'Session19 Constructors,Access specifiers.gslides'
'Session8 Functions.gslides'
'Session9 Lists.gslides'
'SIL CO 1.2. Electric substation.gdoc'
'SIL_CO-1.3_NATIONAL_VOTERS_DAY[1] (1).gdoc'
'SIL_CO-5.2_Dental[1].gdoc'
 SWACH_BHARATH.gdoc
 Table_2.1a__Energy_Consumption__Residential_-_Commercial_-_and_Industrial_Sectors.gsheet
 Table_2.1b__Energy_Consumption__Transportation_Sector_-_Total_End-Use_Sectors_-_and_Electric_Power_Sector.gsheet
'top high paying skills.pdf'
'Trading copy.doc.gdoc'
'Trading Course.gdoc'
'TRADING .gdoc'
'Untitled document (10).gdoc'
'Untitled document (11).gdoc'
'Untitled document (12).gdoc'
'Untitled document (13).gdoc'
'Untitled document (14).gdoc'
'Untitled document (15).gdoc'
'Untitled document (16).gdoc'
'Untitled document (1).gdoc'
'Untitled document (2).gdoc'
'Untitled document (3).gdoc'
'Untitled document (4).gdoc'
'Untitled document (5).gdoc'
'Untitled document (6).gdoc'
'Untitled document (7).gdoc'
'Untitled document (8).gdoc'
'Untitled document (9).gdoc'
'Untitled document.gdoc'
'Untitled presentation.gslides'
'Untitled spreadsheet.gsheet'
'UX Notes.gdoc'
'voice in the spotlight.gdoc'
'VOTERS'\'' SERVICES PORTAL (1).mht'
"VOTERS' SERVICES PORTAL.mht"
 Web_Project_Report.gdoc
'Week 3.gdoc'
'Y2meta.app - Shockwave-Sound - Great Expectations (Uplifting _ Positive _ Pop) [Royalty Free Background Music] (128 kbps).mp3'
 Yashvardhan_Résumé.gdoc

In [ ]:
%cd /content/drive/MyDrive/DVC_Project
!ls -la

[Errno 2] No such file or directory: '/content/drive/MyDrive/DVC_Project'
/content/drive/MyDrive
total 40699
-rw------- 1 root root      183 Feb 21  2025 '1.2 ( St.Got Finals ).gdoc'
-rw------- 1 root root      183 Jan  3  2026  24AD2204-ML-Workbook.gdoc
-rw------- 1 root root      183 Nov  4  2024 '27Introduction To files Create, Read.gslides'
-rw------- 1 root root      183 Nov  4  2024 '28 Append  Defete from file.gslides'
-rw------- 1 root root      183 Feb 21  2025 '3.1 ( Musical Jam Nights ).gdoc'
-rw------- 1 root root      183 Feb 21  2025 '3.2 ( Cricket ).gdoc'
-rw------- 1 root root      183 Apr  7  2025 '5.1 ( Mental Health ).gdoc'
-rw------- 1 root root      183 Jul 31  2025  5_6080418538483357247.gdoc
-rw------- 1 root root      183 Nov  5  2024  5.Iteration.gslides
-rw------- 1 root root      183 Feb 20  2025  7001040005751_ProvisionalCertificate.gdoc
-rw------- 1 root root      183 Nov  5  2024 '7 .Strings.gslides'
-rw------- 1 root root      183 Aug 30  2025 'aggregation and composition.gdoc'
-rw------- 1 root root      183 Feb 15  2025  AI_NOTES.gdoc
-rw------- 1 root root      183 Jul 30  2025 'Arrays in java.gdoc'
-rw------- 1 root root  1798495 Sep  5  2025 "Bhanu's Resume.pdf"
-rw------- 1 root root      183 Mar 11  2025 'Cases-Kasus-- Flow of actions betwe.gdoc'
-rw------- 1 root root      970 Mar 11  2025 'Cases-Kasus-- Flow of actions betwe.txt'
-rw------- 1 root root      183 Oct 16  2025 'CASE STUDY -Document-Finalized (1).gdoc'
-rw------- 1 root root      183 Aug 17  2025 'CASE STUDY -Document-Finalized.gdoc'
-rw------- 1 root root      183 Aug 17  2025 'CASE STUDY -Document.gdoc'
-rw------- 1 root root      183 Feb 21  2025 'CHRISTAMAS CO2.gdoc'
-rw------- 1 root root      183 Apr  6 05:21 'CIAS NOTES.gdoc'
-rw------- 1 root root      183 Dec 12  2025  CIS_CO1_SESSION01.gslides
-rw------- 1 root root      183 Aug 25  2025 'CO1 CO2 questions.gdoc'
-rw------- 1 root root      183 Nov 14  2025 'co-1 sil report.gdoc'
-rw------- 1 root root      183 Sep 17  2025 'CO2 Questions.gdoc'
-rw------- 1 root root      183 Apr 25  2025 'CO-2 REPORT.gdoc'
-rw------- 1 root root      183 Nov 14  2025 'CO-2 SIL REPORT.gdoc'
-rw------- 1 root root      183 Apr  5 07:28 'CO3and 4 ML .gdoc'
-rw------- 1 root root 24254047 Apr 13 01:52 'CO3and 4 ML .pdf'
-rw------- 1 root root  1743561 Nov 11  2025 'CO3_NLP_BEALES METHOD (1).pdf'
-rw------- 1 root root  1766670 Nov 11  2025 'CO_3 NLP_WOLFES METHOD _KKT CONDITIONSpdf.pdf'
-rw------- 1 root root      183 Nov  3  2025 'CO3 PPT.gslides'
-rw------- 1 root root      183 Nov 14  2025 'CO3 SIL REPORT.gdoc'
-rw------- 1 root root      183 Nov 16  2024  CO_4_Lecture_25_GPIO_Programming_ESP32.gslides
-rw------- 1 root root      183 Nov 17  2024  CO_4_Lecture_27_LCD.gslides
-rw------- 1 root root      183 Apr 25  2025 'CO-4 REPORT.gdoc'
-rw------- 1 root root      183 Nov 14  2025 'co-4 sil report.gdoc'
-rw------- 1 root root      183 Apr 25  2025 'CO-5 REPORT.gdoc'
-rw------- 1 root root      183 Apr 25  2025 'CO-5 REPORTS hemi .gdoc'
-rw------- 1 root root      183 Nov 14  2025 'co-5 sil reports.gdoc'
drwx------ 2 root root     4096 Dec 22  2025 'Colab Notebooks'
-rw------- 1 root root      183 Aug 21  2024 'Copy of College Pastel Notes Green variant.gslides'
-rw------- 1 root root      183 Aug 21  2024 'Copy of Private University by Slidesgo.gslides'
-rw------- 1 root root      183 Jan  8  2025 'COVID_19 INDIA1.gsheet'
-rw------- 1 root root      183 Feb 24  2025 'Data structures with Python CO1C02.gdoc'
-rw------- 1 root root      183 Nov  9  2025 'DBMS Notes.gdoc'
-rw------- 1 root root      183 Feb 28  2025 'die Zahlen (2).gdoc'
-rw------- 1 root root      183 Oct 30  2025 'DSV Notes.gdoc'
-rw------- 1 root root      183 Oct 11  2025 'DSV Project Documentation Format.gdoc'
-rw------- 1 root root      183 Oct 31  2024 'DTI AY 2023-24-WIP-1 Even Sem.gslides'
-rw------- 1 root root      183 May  4  2025 'DTI Project Report 2024-25 Odd Sem Template.gdoc'
-rw------- 1 root root      183 Apr 24  2025 'DTW-CO3 & CO4 Document.gdoc'
-rw------- 1 root root      183 Apr  5  2025 'DTW CO 4.gdoc'
-rw------- 1 root root      183 Feb  9  2025 'dtw lab manual.gdoc'
-rw------- 1 root root      183 Feb 18  2025 'DTW_Lab manual.gdoc'
drwx------ 2 root root     4096 May  4  2025 'DTW PROJECT'
-rw------- 1 root root      183 Feb 16  2025 'Employee Payslip _ IFMIS(18).gdoc'
-rw------- 1 root root      183 Jul 28  2025 'Experiments (1).gdoc'
-rw------- 1 root root      183 Oct 12  2025  Experiments.gdoc
-rw------- 1 root root      183 Nov  7  2025 'FEDF Project Documentation sample format.gdoc'
-rw------- 1 root root      183 Feb 21  2025 'FILM MAKING CO3.gdoc'
-rw------- 1 root root      183 Mar 30 04:58 'Foundations of AI-Enabled Edge Computing.gdoc'
-rw------- 1 root root      183 Oct 29  2025 'FRONT END  DEVELOPMENT FRAME WORK ASSIGNMENT .gdoc'
-rw------- 1 root root      183 Feb  6 06:34 'FSAD project abstract.gdoc'
-rw------- 1 root root      183 Feb  4 15:25 'FSAD Theory Short Notes .gdoc'
-rw------- 1 root root      183 Apr 11  2025 'Full Stack Devlopment @ IIT HYDERABAD.gdoc'
-rw------- 1 root root    29521 Sep  8  2025  g1.PNG
-rw------- 1 root root    30469 Sep  8  2025  g2.PNG
-rw------- 1 root root    30949 Sep  8  2025  g3.PNG
-rw------- 1 root root  1664695 Nov 11  2025 'GEOMETRIC PROGRAMMING.pdf'
drwx------ 2 root root     4096 Feb 14 15:04 'Google AI Studio'
-rw------- 1 root root      183 Feb 18  2025 'Google Finance Investment Tracker.gsheet'
-rw------- 1 root root      183 Oct 29  2025 'Group15_OS_Abstract (1).gdoc'
-rw------- 1 root root      183 Aug 21  2024 'Indian mathematicians and statisticians.gslides'
-rw------- 1 root root      183 Jan  3  2026 'LAB BOOK -FOUNDATIONS OF AI-ENABLED EDGE COMPUTING FINAL.gdoc'
-rw------- 1 root root      183 Oct 12  2025 'LIST OF LAB PROGS.gdoc'
-rw------- 1 root root      183 Mar 29 15:17 'ML_Project Documentation (3).gdoc'
-rw------- 1 root root  2360397 Nov 11  2025 'MO_CO4_INFINITE DIMENTIONAL OPTIMIZATION.pdf'
-rw------- 1 root root      183 Apr 30  2025 'MY AI Notes .gdoc'
-rw------- 1 root root   147912 Mar 23  2025  New-675-GB-Graphic-Bundle-v4mujd.pdf
-rw------- 1 root root      183 Aug 12  2025  OOP-R_CO1_Assignment_1.gdoc
-rw------- 1 root root      183 Nov  7  2025 'OOPS Notes.gdoc'
-rw------- 1 root root      183 Jul 14  2025 'Operating system - S6.gdoc'
-rw------- 1 root root      183 Oct 29  2025 'OS abstract format.gdoc'
-rw------- 1 root root      183 Sep 22  2025 'OS hackthon abstract format (1).gdoc'
-rw------- 1 root root      183 Sep 22  2025 'OS hackthon abstract format.gdoc'
-rw------- 1 root root      183 Aug  7  2025 'os _s6-Registeted students listcsv.gdoc'
-rw------- 1 root root      183 Feb 20  2025  pdf_62529861_1708432155549.gdoc
-rw------- 1 root root      183 Sep  9  2025 'project abstract .gdoc'
-rw------- 1 root root   685343 Nov 11  2025 'PSO&ACO_EXAMPLES.pdf'
-rw------- 1 root root      183 Sep  4  2025  Resume.gdoc
-rw------- 1 root root      183 Oct  8  2025 'Review1 form and students can take printout.gdoc'
-rw------- 1 root root      183 Nov  4  2024  S18_DC_Motor.gslides
-rw------- 1 root root      183 Nov 10  2024  S19_Servo_Motor.gslides
-rw------- 1 root root      183 Nov  5  2024  S20_Stepper_Motor.gslides
-rw------- 1 root root      183 Nov  8  2024  S21_Motor_Driver_Circuit.gslides
-rw------- 1 root root      183 Nov  8  2024  S23_Opto_Couplers.gslides
-rw------- 1 root root      183 Sep 15  2025 'sample ppt format(1).gslides'
drwx------ 2 root root     4096 Jun 30 18:26 'Saved from Chrome'
-rw------- 1 root root      183 Apr  7  2025 'self awarness.gdoc'
-rw------- 1 root root      183 Nov  7  2024 'Session11 Sets.gslides'
-rw------- 1 root root      183 Nov  7  2024 'Session12 Tuple.gslides'
-rw------- 1 root root      183 Nov  7  2024 'Session19 Constructors,Access specifiers.gslides'
-rw------- 1 root root      183 Nov  5  2024 'Session8 Functions.gslides'
-rw------- 1 root root      183 Nov  5  2024 'Session9 Lists.gslides'
-rw------- 1 root root      183 Apr  7  2025 'SIL CO 1.2. Electric substation.gdoc'
-rw------- 1 root root      183 Apr 11  2025 'SIL_CO-1.3_NATIONAL_VOTERS_DAY[1] (1).gdoc'
-rw------- 1 root root      183 Apr  7  2025 'SIL_CO-5.2_Dental[1].gdoc'
-rw------- 1 root root      183 Feb 21  2025  SWACH_BHARATH.gdoc
-rw------- 1 root root      183 Jan  9  2026  Table_2.1a__Energy_Consumption__Residential_-_Commercial_-_and_Industrial_Sectors.gsheet
-rw------- 1 root root      183 Jan  9  2026  Table_2.1b__Energy_Consumption__Transportation_Sector_-_Total_End-Use_Sectors_-_and_Electric_Power_Sector.gsheet
-rw------- 1 root root   152859 Aug  1  2025 'top high paying skills.pdf'
-rw------- 1 root root      183 Jan 12  2025 'Trading copy.doc.gdoc'
-rw------- 1 root root      183 Oct 10  2025 'Trading Course.gdoc'
-rw------- 1 root root      183 Jan 14  2025 'TRADING .gdoc'
-rw------- 1 root root      183 Jul 13  2025 'Untitled document (10).gdoc'
-rw------- 1 root root      183 May  4  2025 'Untitled document (11).gdoc'
-rw------- 1 root root      183 Apr 25  2025 'Untitled document (12).gdoc'
-rw------- 1 root root      183 Apr 25  2025 'Untitled document (13).gdoc'
-rw------- 1 root root      183 Feb 10  2025 'Untitled document (14).gdoc'
-rw------- 1 root root      183 Jan 14  2025 'Untitled document (15).gdoc'
-rw------- 1 root root      183 Dec 23  2024 'Untitled document (16).gdoc'
-rw------- 1 root root      183 Mar 13 16:10 'Untitled document (1).gdoc'
-rw------- 1 root root      183 Mar 13 05:25 'Untitled document (2).gdoc'
-rw------- 1 root root      183 Feb  2 07:37 'Untitled document (3).gdoc'
-rw------- 1 root root      183 Sep 23  2025 'Untitled document (4).gdoc'
-rw------- 1 root root      183 Sep  9  2025 'Untitled document (5).gdoc'
-rw------- 1 root root      183 Sep  4  2025 'Untitled document (6).gdoc'
-rw------- 1 root root      183 Aug 10  2025 'Untitled document (7).gdoc'
-rw------- 1 root root      183 Jul 25  2025 'Untitled document (8).gdoc'
-rw------- 1 root root      183 Jul 25  2025 'Untitled document (9).gdoc'
-rw------- 1 root root      183 Dec 23  2024 'Untitled document.gdoc'
-rw------- 1 root root      183 Aug 29  2024 'Untitled presentation.gslides'
-rw------- 1 root root      183 Jan  4  2025 'Untitled spreadsheet.gsheet'
-rw------- 1 root root      183 Sep 14  2025 'UX Notes.gdoc'
-rw------- 1 root root      183 Apr 11  2025 'voice in the spotlight.gdoc'
-rw------- 1 root root  1732089 Jul 13 16:34 'VOTERS'\'' SERVICES PORTAL (1).mht'
-rw------- 1 root root  1732111 Jul 13 16:34 "VOTERS' SERVICES PORTAL.mht"
-rw------- 1 root root      183 May  4  2025  Web_Project_Report.gdoc
-rw------- 1 root root      183 Jul 30  2025 'Week 3.gdoc'
-rw------- 1 root root  3462513 Aug  3  2024 'Y2meta.app - Shockwave-Sound - Great Expectations (Uplifting _ Positive _ Pop) [Royalty Free Background Music] (128 kbps).mp3'
-rw------- 1 root root      183 Sep  3  2025  Yashvardhan_Résumé.gdoc

In [ ]:
!git status

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

In [ ]:
!git add .

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

In [ ]:
# Step 11: Correctly Commit Version 1 and then Version 2

# Ensure we are in the correct DVC project directory
%cd /content/DVC_Project

# Clean up existing git repository and dvc files to start fresh
!rm -rf .git
!rm -rf .dvc
!rm -f student.csv.dvc

# Initialize Git and DVC again
!git init
!dvc init

# Set Git user configuration (if not already set globally or for this repo)
# These should ideally be set once, but re-setting for robustness after reset
!git config user.name "chary"
!git config user.email "charybhanuprasad07@gmail.com"

# --- Create and Commit Dataset Version 1 ---
# Create 'Dataset Version 1' (original data without 'Sita')
import pandas as pd
data_v1 = {
    "Student": ["Ravi", "Priya", "Anu", "Rahul"],
    "Marks": [90, 85, 78, 95]
}
df_v1 = pd.DataFrame(data_v1)
df_v1.to_csv("student.csv", index=False)

# Add 'Dataset Version 1' to DVC
!dvc add student.csv

# Add DVC-related files and the dvc-tracked file to Git
!git add .gitignore .dvcignore .dvc/config student.csv.dvc

# Commit Dataset Version 1
!git commit -m "Dataset Version 1"

# --- Create and Commit Dataset Version 2 ---
# Create 'Dataset Version 2' (adding 'Sita')
data_v2 = {
    "Student": ["Ravi", "Priya", "Anu", "Rahul", "Sita"],
    "Marks": [90, 85, 78, 95, 88]
}
df_v2 = pd.DataFrame(data_v2)
df_v2.to_csv("student.csv", index=False)

# Add the modified 'student.csv' (version 2) to DVC
!dvc add student.csv

# Add the updated student.csv.dvc file to Git
!git add student.csv.dvc

# Commit Dataset Version 2
!git commit -m "Dataset Version 2"

# Display the corrected Git version history
!git log --oneline

/content/DVC_Project
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/DVC_Project/.git/
Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/treeverse/dvc>
⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s]
Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

Checking out /content/DVC_Project/student.csv:   0% 0/1 [00:00<?, ?files/s]
  0% 0/1 [00:00<?, ?files/s{'info': ''}]
Adding...: 100% 1/1 [00:00<00:00, 25.04file/s{'info': ''}]

To track the changes with git, run:

	git add student.csv.dvc

To enable auto staging, run:

	dvc config core.autostage true
[master (root-commit) 81d6359] Dataset Version 1
 5 files changed, 12 insertions(+)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvcignore
 create mode 100644 .gitignore
 create mode 100644 student.csv.dvc
⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s]
Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

Checking out /content/DVC_Project/student.csv:   0% 0/1 [00:00<?, ?files/s]
  0% 0/1 [00:00<?, ?files/s{'info': ''}]
Adding...: 100% 1/1 [00:00<00:00, 17.26file/s{'info': ''}]

To track the changes with git, run:

	git add student.csv.dvc

To enable auto staging, run:

	dvc config core.autostage true
[master 365e872] Dataset Version 2
 1 file changed, 2 insertions(+), 2 deletions(-)
365e872 (HEAD -> master) Dataset Version 2
81d6359 Dataset Version 1

In [ ]:
# Step 12: Modify Dataset
import pandas as pd
df = pd.read_csv("/content/DVC_Project/student.csv")
df.loc[len(df)] = ["Sita", 88]
df.to_csv("/content/DVC_Project/student.csv", index=False)
df

  Student  Marks
0    Ravi     90
1   Priya     85
2     Anu     78
3   Rahul     95
4    Sita     88

In [ ]:
# step 12: Modify Dataset
import pandas as pd
df = pd.read_csv("/content/DVC_Project/student.csv")
df.loc[len(df)] = ["Sita", 88]
df.to_csv("student.csv", index=False)
df

  Student  Marks
0    Ravi     90
1   Priya     85
2     Anu     78
3   Rahul     95
4    Sita     88
5    Sita     88

In [ ]:
# Step 13: Track New Version
!pip install dvc
!dvc version

Requirement already satisfied: dvc in /usr/local/lib/python3.12/dist-packages (3.67.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (26.1.0)
Requirement already satisfied: celery in /usr/local/lib/python3.12/dist-packages (from dvc) (5.6.3)
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.4.6)
Requirement already satisfied: configobj>=5.0.9 in /usr/local/lib/python3.12/dist-packages (from dvc) (5.0.9)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.9.0)
Requirement already satisfied: dpath<3,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.2.0)
Requirement already satisfied: dulwich in /usr/local/lib/python3.12/dist-packages (from dvc) (1.2.12)
Requirement already satisfied: dvc-data<3.19.0,>=3.18.2 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.18.3)
Requirement already satisfied: dvc-http>=2.29.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.32.0)
Requirement already satisfied: dvc-objects in /usr/local/lib/python3.12/dist-packages (from dvc) (5.2.0)
Requirement already satisfied: dvc-render<2,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.0.2)
Requirement already satisfied: dvc-studio-client<1,>=0.21 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.23.0)
Requirement already satisfied: dvc-task<1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.40.2)
Requirement already satisfied: flatten-dict<1,>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.5.0)
Requirement already satisfied: flufl.lock<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (9.1.0)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2025.3.0)
Requirement already satisfied: funcy>=1.14 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.0)
Requirement already satisfied: grandalf<1,>=0.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.8)
Requirement already satisfied: gto<2,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.10.1)
Requirement already satisfied: hydra-core>=1.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.3.4)
Requirement already satisfied: iterative-telemetry>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.0.10)
Requirement already satisfied: kombu in /usr/local/lib/python3.12/dist-packages (from dvc) (5.6.2)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.6.1)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (from dvc) (2.3.1)
Requirement already satisfied: packaging>=19 in /usr/local/lib/python3.12/dist-packages (from dvc) (26.2)
Requirement already satisfied: pathspec<2,>=0.10.3 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.1.1)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.10.0)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.12/dist-packages (from dvc) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.0.1)
Requirement already satisfied: pygtrie>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.5.0)
Requirement already satisfied: pyparsing>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.3.2)
Requirement already satisfied: requests>=2.22 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.32.4)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.12/dist-packages (from dvc) (13.9.4)
Requirement already satisfied: ruamel.yaml>=0.17.11 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.19.1)
Requirement already satisfied: scmrepo<4,>=3.5.2 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.6.2)
Requirement already satisfied: shortuuid>=0.5 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.0.13)
Requirement already satisfied: shtab<2,>=1.3.4 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.9.2)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.9.0)
Requirement already satisfied: tomlkit>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.14.0)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.67.3)
Requirement already satisfied: voluptuous>=0.11.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.16.0)
Requirement already satisfied: zc.lockfile>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.0)
Requirement already satisfied: dictdiffer>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.10.0)
Requirement already satisfied: diskcache>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (5.6.3)
Requirement already satisfied: sqltrie<1,>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.11.2)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.11.9)
Requirement already satisfied: aiohttp-retry>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from dvc-http>=2.29.0->dvc) (2.9.1)
Requirement already satisfied: billiard<5.0,>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (4.2.4)
Requirement already satisfied: vine<6.0,>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (5.1.0)
Requirement already satisfied: click<9.0,>=8.1.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (8.4.2)
Requirement already satisfied: click-didyoumean>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (0.3.1)
Requirement already satisfied: click-repl>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (0.3.0)
Requirement already satisfied: click-plugins>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (1.1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (2.9.0.post0)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (5.4.4)
Requirement already satisfied: atpublic in /usr/local/lib/python3.12/dist-packages (from flufl.lock<10,>=8.1.0->dvc) (5.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (2.13.4)
Requirement already satisfied: pydantic-settings>=2 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (2.14.2)
Requirement already satisfied: semver>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (3.0.4)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.1->dvc) (4.9.3)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.7->dvc) (1.4.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.7->dvc) (3.29.7)
Requirement already satisfied: amqp<6.0.0,>=5.1.1 in /usr/local/lib/python3.12/dist-packages (from kombu->dvc) (5.3.1)
Requirement already satisfied: tzdata>=2025.2 in /usr/local/lib/python3.12/dist-packages (from kombu->dvc) (2026.3)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from omegaconf->dvc) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (2.20.0)
Requirement already satisfied: gitpython>3 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (3.1.51)
Requirement already satisfied: pygit2>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (1.19.3)
Requirement already satisfied: asyncssh<3,>=2.13.1 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (2.24.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from zc.lockfile>=1.2.1->dvc) (75.2.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (3.14.1)
Requirement already satisfied: cryptography>=48.0.1 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (49.0.0)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (4.16.0)
Requirement already satisfied: prompt-toolkit>=3.0.36 in /usr/local/lib/python3.12/dist-packages (from click-repl>=0.2.0->celery->dvc) (3.0.52)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython>3->scmrepo<4,>=3.5.2->dvc) (4.0.12)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2->gto<2,>=1.6.0->dvc) (1.2.2)
Requirement already satisfied: cffi>=2.0 in /usr/local/lib/python3.12/dist-packages (from pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (2.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->celery->dvc) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.24.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0->pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc) (5.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.8.2)
DVC version: 3.67.1 (pip)
-------------------------
Platform: Python 3.12.13 on Linux-6.6.122+-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 3.18.3
	dvc_objects = 5.2.0
	dvc_render = 1.0.2
	dvc_task = 0.40.2
	scmrepo = 3.6.2
Supports:
	http (aiohttp = 3.14.1, aiohttp-retry = 2.9.1),
	https (aiohttp = 3.14.1, aiohttp-retry = 2.9.1)
Config:
	Global: /root/.config/dvc
	System: /etc/xdg/dvc

In [ ]:
%cd /content/drive/MyDrive/DVC_Project

[Errno 2] No such file or directory: '/content/drive/MyDrive/DVC_Project'
/content/drive/MyDrive

In [ ]:
%cd /content/DVC_Project
!dvc add student.csv

/content/DVC_Project
⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s]
Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

Checking out /content/DVC_Project/student.csv:   0% 0/1 [00:00<?, ?files/s]
  0% 0/1 [00:00<?, ?files/s{'info': ''}]
Adding...: 100% 1/1 [00:00<00:00, 30.48file/s{'info': ''}]

To track the changes with git, run:

	git add student.csv.dvc

To enable auto staging, run:

	dvc config core.autostage true

In [ ]:
# Step 14 : Commit version 2
!git add .
!git commit -m "Dataset Version 2"

[master (root-commit) 8561f5b] Dataset Version 2
 5 files changed, 12 insertions(+)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvcignore
 create mode 100644 .gitignore
 create mode 100644 student.csv.dvc

In [ ]:
# Step 15: View Version History
!git log --oneline

8561f5b (HEAD -> master) Dataset Version 2

In [ ]:
# Step 16: Restore Previous Version
!git checkout HEAD~1

error: pathspec 'HEAD~1' did not match any file(s) known to git

In [ ]:
!dvc checkout

Building workspace index          |1.00 [00:00, 28.4entry/s]
Comparing indexes          |2.00 [00:00, 1.73kentry/s]
Applying changes          |0.00 [00:00,     ?file/s]

In [ ]:
# Step 17: Verify Dataset
import pandas as pd
pd.read_csv("student.csv")

  Student  Marks
0    Ravi     90
1   Priya     85
2     Anu     78
3   Rahul     95
4    Sita     88

In [ ]:
# step 18: Modify Dataset
import pandas as pd
df = pd.read_csv("/content/DVC_Project/student.csv")
df.loc[len(df)] = ["harshini", 88]
df.to_csv("student.csv", index=False)
df

    Student  Marks
0      Ravi     90
1     Priya     85
2       Anu     78
3     Rahul     95
4      Sita     88
5  harshini     88

In [ ]:
# Step 19: Track New Version
!pip install dvc
!dvc version

Requirement already satisfied: dvc in /usr/local/lib/python3.12/dist-packages (3.67.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (26.1.0)
Requirement already satisfied: celery in /usr/local/lib/python3.12/dist-packages (from dvc) (5.6.3)
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.4.6)
Requirement already satisfied: configobj>=5.0.9 in /usr/local/lib/python3.12/dist-packages (from dvc) (5.0.9)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.9.0)
Requirement already satisfied: dpath<3,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.2.0)
Requirement already satisfied: dulwich in /usr/local/lib/python3.12/dist-packages (from dvc) (1.2.12)
Requirement already satisfied: dvc-data<3.19.0,>=3.18.2 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.18.3)
Requirement already satisfied: dvc-http>=2.29.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.32.0)
Requirement already satisfied: dvc-objects in /usr/local/lib/python3.12/dist-packages (from dvc) (5.2.0)
Requirement already satisfied: dvc-render<2,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.0.2)
Requirement already satisfied: dvc-studio-client<1,>=0.21 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.23.0)
Requirement already satisfied: dvc-task<1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.40.2)
Requirement already satisfied: flatten-dict<1,>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.5.0)
Requirement already satisfied: flufl.lock<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (9.1.0)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2025.3.0)
Requirement already satisfied: funcy>=1.14 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.0)
Requirement already satisfied: grandalf<1,>=0.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.8)
Requirement already satisfied: gto<2,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.10.1)
Requirement already satisfied: hydra-core>=1.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.3.4)
Requirement already satisfied: iterative-telemetry>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.0.10)
Requirement already satisfied: kombu in /usr/local/lib/python3.12/dist-packages (from dvc) (5.6.2)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.6.1)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (from dvc) (2.3.1)
Requirement already satisfied: packaging>=19 in /usr/local/lib/python3.12/dist-packages (from dvc) (26.2)
Requirement already satisfied: pathspec<2,>=0.10.3 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.1.1)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.10.0)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.12/dist-packages (from dvc) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.0.1)
Requirement already satisfied: pygtrie>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.5.0)
Requirement already satisfied: pyparsing>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.3.2)
Requirement already satisfied: requests>=2.22 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.32.4)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.12/dist-packages (from dvc) (13.9.4)
Requirement already satisfied: ruamel.yaml>=0.17.11 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.19.1)
Requirement already satisfied: scmrepo<4,>=3.5.2 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.6.2)
Requirement already satisfied: shortuuid>=0.5 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.0.13)
Requirement already satisfied: shtab<2,>=1.3.4 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.9.2)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.9.0)
Requirement already satisfied: tomlkit>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.14.0)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.67.3)
Requirement already satisfied: voluptuous>=0.11.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.16.0)
Requirement already satisfied: zc.lockfile>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.0)
Requirement already satisfied: dictdiffer>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.10.0)
Requirement already satisfied: diskcache>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (5.6.3)
Requirement already satisfied: sqltrie<1,>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.11.2)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.11.9)
Requirement already satisfied: aiohttp-retry>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from dvc-http>=2.29.0->dvc) (2.9.1)
Requirement already satisfied: billiard<5.0,>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (4.2.4)
Requirement already satisfied: vine<6.0,>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (5.1.0)
Requirement already satisfied: click<9.0,>=8.1.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (8.4.2)
Requirement already satisfied: click-didyoumean>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (0.3.1)
Requirement already satisfied: click-repl>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (0.3.0)
Requirement already satisfied: click-plugins>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (1.1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (2.9.0.post0)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (5.4.4)
Requirement already satisfied: atpublic in /usr/local/lib/python3.12/dist-packages (from flufl.lock<10,>=8.1.0->dvc) (5.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (2.13.4)
Requirement already satisfied: pydantic-settings>=2 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (2.14.2)
Requirement already satisfied: semver>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (3.0.4)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.1->dvc) (4.9.3)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.7->dvc) (1.4.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.7->dvc) (3.29.7)
Requirement already satisfied: amqp<6.0.0,>=5.1.1 in /usr/local/lib/python3.12/dist-packages (from kombu->dvc) (5.3.1)
Requirement already satisfied: tzdata>=2025.2 in /usr/local/lib/python3.12/dist-packages (from kombu->dvc) (2026.3)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from omegaconf->dvc) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (2.20.0)
Requirement already satisfied: gitpython>3 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (3.1.51)
Requirement already satisfied: pygit2>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (1.19.3)
Requirement already satisfied: asyncssh<3,>=2.13.1 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (2.24.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from zc.lockfile>=1.2.1->dvc) (75.2.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (3.14.1)
Requirement already satisfied: cryptography>=48.0.1 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (49.0.0)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (4.16.0)
Requirement already satisfied: prompt-toolkit>=3.0.36 in /usr/local/lib/python3.12/dist-packages (from click-repl>=0.2.0->celery->dvc) (3.0.52)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython>3->scmrepo<4,>=3.5.2->dvc) (4.0.12)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2->gto<2,>=1.6.0->dvc) (1.2.2)
Requirement already satisfied: cffi>=2.0 in /usr/local/lib/python3.12/dist-packages (from pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (2.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->celery->dvc) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.24.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0->pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc) (5.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.8.2)
DVC version: 3.67.1 (pip)
-------------------------
Platform: Python 3.12.13 on Linux-6.6.122+-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 3.18.3
	dvc_objects = 5.2.0
	dvc_render = 1.0.2
	dvc_task = 0.40.2
	scmrepo = 3.6.2
Supports:
	http (aiohttp = 3.14.1, aiohttp-retry = 2.9.1),
	https (aiohttp = 3.14.1, aiohttp-retry = 2.9.1)
Config:
	Global: /root/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: None
Workspace directory: overlay on overlay
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/ae2d5e2a2d79db3cefbeef14fcaf6bb2

In [ ]:
%cd /content/DVC_Project

/content/DVC_Project

In [ ]:
%cd /content/DVC_Project
!dvc add student.csv

/content/DVC_Project
⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s]
Adding student.csv to cache:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

Checking out /content/DVC_Project/student.csv:   0% 0/1 [00:00<?, ?files/s]
  0% 0/1 [00:00<?, ?files/s{'info': ''}]
Adding...: 100% 1/1 [00:00<00:00, 22.54file/s{'info': ''}]

To track the changes with git, run:

	git add student.csv.dvc

To enable auto staging, run:

	dvc config core.autostage true

In [ ]:
# Step 20 : Commit version 2
!git add .
!git commit -m "Dataset Version 3"

[master 5d94e88] Dataset Version 3
 1 file changed, 2 insertions(+), 2 deletions(-)

In [ ]:
# Step 15: View Version History
!git log --oneline

5d94e88 (HEAD -> master) Dataset Version 3
365e872 Dataset Version 2
81d6359 Dataset Version 1